### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by mohamad-d-zz** [jaleelx98/Rambo-Bot#1]
? [>] Insert Username: ************
? [>] Insert Password: *************
? [>] Insert Username Target (Without @[at]):************
? [>] Number of Accounts per Delay: 10
? [>] Insert Sleep (MiliSeconds): 900000

 [?] Try to Login . . .
(node:52961) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:52961) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
 [!] Login Succsess, [?] Try To Get ID & Followers Target . . .
TypeError: Cannot read property '0' of undefined
    at Target (/Users/********/Downloads/Rambo-Bot-main/src/commentLike-byPeople.js:1:3450)
    at async Excute (/Users/*******/Downloads/Rambo-Bot-main/src/commentLike-byPeople.js:1:6413)

hi
please help me
and i need create config file for save username and password and other options, because i need run bot to my server with nohup in background.
tnx

**Comment by jaleelx98** [comment]
use another account and try again...!

**Comment by mohamad-d-zz** [comment]
yes i test with another account but dont work. it work only for first one in first account
tnx
